const ActionsWorkers = {
   FETCH_WORKERS: 'FETCH_WORKERS',
   FETCH_FILTERS: 'FETCH_FILTERS',
   FETCH_SEARCH: 'FETCH_SEARCH',
   FETCH_SECTION: 'FETCH_SECTION',
   FETCH_PAY_FROM: 'FETCH_PAY_FROM',
   FETCH_PAY_TO: 'FETCH_PAY_TO',
   FETCH_ADD_WORKER: 'FETCH_ADD_WORKER',
};

const MutationsWorkers = {
   SET_WORKERS: 'SET_WORKERS',
   SET_FETCH_FILTERS: 'SET_FETCH_FILTERS',
   SET_SEARCH: 'SET_SEARCH',
   SET_SECTION: 'SET_SECTION',
   SET_PAY_FROM: 'SET_PAY_FROM',
   SET_PAY_TO: 'SET_PAY_TO',
   SET_ADD_WORKER: 'SET_ADD_WORKER',
};

const GettersWorkers = {
   GET_WORKERS: 'GET_WORKERS',
   GET_WORKERS_SECTION: 'GET_WORKERS_SECTION',
   GET_WORKERS_SECTION_ALL: 'GET_WORKERS_SECTION_ALL',
   GET_WORKERS_PAY_SECTION: 'GET_WORKERS_PAY_SECTION',
};

export { ActionsWorkers, MutationsWorkers, GettersWorkers };
