const ActionsWorkers = {
   FETCH_WORKERS: 'FETCH_WORKERS',
   FETCH_SEARCH_WORKERS: 'FETCH_SEARCH_WORKERS',
   FETCH_SELECT_FILTERS_WORKERS: 'FETCH_SELECT_FILTERS_WORKERS',
};

const MutationsWorkers = {
   SET_WORKERS: 'SET_WORKERS',
   SET_SEARCH_WORKERS: 'SET_SEARCH_WORKERS',
};

const GettersWorkers = {
   GET_WORKERS: 'GET_WORKERS',
   GET_WORKERS_SECTION: 'GET_WORKERS_SECTION',
   GET_WORKERS_PAY_SECTION: 'GET_WORKERS_PAY_SECTION',
};

export { ActionsWorkers, MutationsWorkers, GettersWorkers };
