const ActionsWorkers = {
   FETCH_WORKERS: 'FETCH_WORKERS',
   FETCH_FILTERS: 'FETCH_FILTERS',
   FETCH_SEARCH: 'FETCH_SEARCH',
   FETCH_SECTION: 'FETCH_SECTION',
};

const MutationsWorkers = {
   SET_WORKERS: 'SET_WORKERS',
   SET_FETCH_FILTERS: 'SET_FETCH_FILTERS',
   SET_SEARCH: 'SET_SEARCH',
   SET_SECTION: 'SET_SECTION',
};

const GettersWorkers = {
   GET_WORKERS: 'GET_WORKERS',
   GET_WORKERS_SECTION: 'GET_WORKERS_SECTION',
   GET_WORKERS_PAY_SECTION: 'GET_WORKERS_PAY_SECTION',
};

export { ActionsWorkers, MutationsWorkers, GettersWorkers };
